server:
  port: 8080

spring:
  application:
    name: zlt-nacos-consumer

dubbo:
  application:
    name: ${spring.application.name}
    #provider注册模式，可选值 interface(接口级)、instance(应用级)、all，默认是all(双注册)
    register-mode: instance
    #consumer服务发现模式
    service-discovery:
      # FORCE_INTERFACE，只消费接口级地址，如无地址则报错，单订阅 2.x 地址
      # APPLICATION_FIRST，智能决策接口级/应用级地址，双订阅
      # FORCE_APPLICATION，只消费应用级地址，如无地址则报错，单订阅 3.x 地址
      migration: FORCE_APPLICATION
  registry:
    address: nacos://192.168.28.130:8848
  consumer:
    timeout: 3000
